---
sections:
  - label: Posts
    name: posts
    path: _posts
    templates:
      - simple_post
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - name: authors
    label: Authors
    path: _authors
    templates:
      - author
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
